### ISSUE TITLE
Why not do it agnostic to underlying hardware?

### ISSUE THREAD

**Issue by jayrmotta** [SatoshiPortal/cyphernode#1]
It seems this repo and also SatoshiPortal/dockers are heavily reliant on Raspberry Pi.

This is awesome but for those like me willing to experiment a full Bitcoin and Lightning network it becomes an entry barrier, since I don't have a Raspberry yet.

Do you guys see value in changing it to be agnostic?

**Comment by Kexkey** [comment]
It's already the case.

In the docs, we assume being on an RPi for simplicity.  When, for instance, we give commands like chown, we must provide the host's user name.  Since we don't know your username, we used "pi" but you should replace it by yours.

For containers found in https://github.com/SatoshiPortal/dockers, you will find an x86 directory when appropriate.

In the bin/ directory, you will find precompiled versions of lightning-cli for ARM (RPi) and x86 for convenience, but you should copy the binary you built from sources in your c-lightning container.
