### ISSUE TITLE
Separate Bitcoin Core RPC and Protocol ports

### ISSUE THREAD

**Issue by Kexkey** [SatoshiPortal/cyphernode#130]
In setup, we ask if we want to expose Bitcoin ports (RPC and Protocol).  That should be 2 different configs.

Do you want to expose RPC port?
Do you want to expose Protocol port?

**Comment by phillamy** [comment]
Currently, the installer says:

_? Installer: Expose bitcoin full node outside of the docker network?

By default, Bitcoin node port (P2P port) will NOT be published outside of Docker.
Do you want to expose it so that your node can be accessed from outside of the
Docker network?_

Should become 2 separate questions :

1)
? Installer: Expose bitcoin full node **Protocol port** outside of the docker network?

By default, Bitcoin node **Protocol port** will NOT be published outside of Docker.
Do you want to expose it so that your node can be accessed from outside of the
Docker network?

2)
? Installer: Expose bitcoin full node **RPC port** outside of the docker network?

By default, Bitcoin node **RPC port** will NOT be published outside of Docker.
Do you want to expose it so that your node can be accessed from outside of the
Docker network?

@Kexkey : Is it what you meant ?

**Comment by phillamy** [comment]
PR:
? Installer: Expose bitcoin full node P2P port outside of the docker network?

By default, Bitcoin node port (P2P port) will NOT be published outside of Docker.
Do you want to expose it so that your node can be accessed from outside of the
Docker network?

 No

**Comment by Kexkey** [comment]
https://github.com/SatoshiPortal/cyphernode/pull/236
