### ISSUE TITLE
Gatekeeper cert not regenerating

### ISSUE THREAD

**Issue by xsats** [SatoshiPortal/cyphernode#194]
Hi @Kexkey, hope you're well!

I've been playing with a deployment of Cyphernode today and, when attempting to add an extra host (the IP address of a local node running Cyphernode) using the setup.sh script, for some reason the certificate is not getting updated to include the extra IP. I also tried directly changing the default hostname to my desired IP in the setup.sh script but to no avail. So I was wondering if I'm doing something wrong or if this is something you've encountered already.

Also wondering if commit a03c0265e8dce74b53646fd2ceb38015648409ed is related to this in some way.

**Comment by Kexkey** [comment]
Hi @xsats !

Interesting!  If I understand correctly, you are exposing the gatekeeper outside of the Docker network and simply changing the host IP address would cause problems with the gatekeeper's certs because even after re-running setup and changing/adding the new IP, they don't regenerate so still have previous IP.

@schulterklopfer do you have an idea of what is going on before I dive into this problem?

**Comment by xsats** [comment]
Yep as you described - exposing the gatekeeper and changing the host IP, then re-running setup and adding the new IP doesn't seem to regenerate a new TLS cert that includes the newly added IP.

It's not hugely urgent but I thought I'd report the experience back here in case others come across it/theres an easy solution. Thanks!
