### ISSUE TITLE
Bad Request on first install

### ISSUE THREAD

**Issue by jacobbdavis1991** [SatoshiPortal/cyphernode#21]
after fresh install using step by step guide I get a bad request when running this command.
echo "GET /getbalance" | docker run --rm -i --network=cyphernodenet alpine nc cyphernode:8888 -
Respone:HTTP/1.1 400 Bad Request
Content-Type: application/json
Content-Length: 0
I have everything running on one linux machine like the step by step suggests.
Thanks for your help.
Jacob Davis

**Comment by Kexkey** [comment]
Hi Jacob, what's the output of ```docker service ls``` and ```docker ps```?  Is your bitcoind running in the cyphernode stack?  Make sure the information found in ```proxy_docker/env.properties``` about the Bitcoin node is the same as in your bitcoin.conf file (found in ~/btcdata if you followed the step by step install).  Do you have this in your bitcoin.conf file:

```
wallet=watching01.dat
wallet=spending01.dat
```

**Comment by jacobbdavis1991** [comment]
![screen shot 2018-10-28 at 10 43 38 am](https://user-images.githubusercontent.com/35181018/47619634-60e35800-da9e-11e8-93ae-5d35f6527074.png)
![screen shot 2018-10-28 at 10 43 42 am](https://user-images.githubusercontent.com/35181018/47619637-62ad1b80-da9e-11e8-9d82-56fe38030b28.png)
how do I access btcnode if bitcoin is not working or running?

**Comment by Kexkey** [comment]
You have to look at bitcoind debug log in ```~/btcdata/debug.log``` or ```~/btcdata/testnet3/debug.log``` if you are on testnet.  You will find hints on why the node is not able to run.  Maybe you can reapply the permissions on ~/btcdata fold as stated at the end of the docs.  Anyway give me some info found in debug file.

Oh and clightningnode will not start until bitcoin node is up and running.

**Comment by jacobbdavis1991** [comment]
hello! okay I got it working, I was using ubuntu instead of Debian and I guess that was the issue. thank you for your time! I am using Debian now and it all works as expected!

**Comment by Kexkey** [comment]
That’s great news!  Please keep us posted on your CypherNode use and let us know if you’d like to see new features in it!  :-)

**Comment by jacobbdavis1991** [comment]
alright so testnet works great, so thanks. but when i try to run actual node it has an issue binding on 8332. I now get bad request when trying to use the test commands. did i miss something? I have changed the proxy_docker/env.properties to :8332 . but still nothing. thanks in advance

**Comment by Kexkey** [comment]
Hi Jacob!  Sorry for the delay in answering.

For the authapi not working as expected, did you install cyphernode on a Raspberry Pi?  There's currently a problem because the nginx:alpine image for ARM is not available anymore in the Docker hub... not sure why.  It was available 5 weeks ago.  I am working on it.  If that's not your case, I need more details.  Does the authapi container running correctly?  What do you see in the logs?  Did you create new keys and use the created keys for your requests?

As for the confirmations, for now there's only 0-conf and 1-conf as the Bitcoin Core node only supports those as its notifywallet feature.  But we can add that feature (callbacks on variable number of confirmations) in the near future.  It wouldn't be very hard, having a 1-minute cron job checking the transaction with the node would be ok.

**Comment by Kexkey** [comment]
No more follow-ups, I'll close but can be reopened if needed.
