### ISSUE TITLE
Lightning Network "PAY" Sanity Check

### ISSUE THREAD

**Issue by FrancisPouliot** [SatoshiPortal/cyphernode#44]
**Problem**: when sending bitcoins to users with LN on the Bylls and Bull Bitcoin apps, we must ensure that the end-user is able to sucessfully generate a Bolt11 invoice that is compatible the payment we want to perform. Unlike LN-enable merchants, in this case the recipient **does not** decide what kind of Bolt 11 invoice he creates. We decide it in advance.

1. User will create a "payout-request" to cyphernode with the following expected fields:
- msatoshi
2. User will send a "bolt 11" string to cyphernode
3. Cyphernode will call the "decode" function.
4. Cyphernode will compare the expected msatoshi and check that currency is Bitcoin.
5. If expected amount is the same and Bitcoin is currency, pay.
6. If not, return "bad invoice" with error.

**Comment by Kexkey** [comment]
ln_pay already works like that.  It receives a bolt11 string, expected_msatoshi and expected_description in parameters, decodes the bolt11 string, compare amount and description and pay if they are equal.

In your example, I assume "User" is the cyphernode client app (BullBitcoin app), not the end-user receiving the payment?  Since I don't think the end-user won't have access to cyphernode.

Not sure why #1.

**Comment by FrancisPouliot** [comment]
ok i didnt know it worked like that
